# Generated by Django 3.1.6 on 2021-02-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210221_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
