# Generated by Django 3.1.6 on 2021-02-19 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس کتاب')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images', verbose_name='تصویر کتاب')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تشکیل کتاب')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('number_of_pages', models.IntegerField(verbose_name='تعداد صفحات کتاب')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('percent', models.IntegerField(verbose_name='درصد تخفیف')),
                ('offer', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتابها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('photo', models.ImageField(upload_to='cat_images', verbose_name='تصویر دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='امتیاز')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='gallery.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز ستاره\u200cای',
                'verbose_name_plural': 'امتیازهای ستاره\u200cای',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.book', verbose_name='کتاب')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='gallery.Category', verbose_name='دسته\u200cبندی'),
        ),
    ]
