# Generated by Django 3.1.6 on 2021-02-19 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='سفارش شده')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.book', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آیتم سفارشی',
                'verbose_name_plural': 'آیتم های سفارشی',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع')),
                ('ordered_date', models.DateTimeField(verbose_name='تاریخ سفارش')),
                ('ordered', models.BooleanField(default=False, verbose_name='سفارش شده')),
                ('ordered_price', models.IntegerField(default=0, verbose_name='مبلغ پرداخت شده')),
                ('being_delivered', models.BooleanField(default=False, verbose_name='ارسال')),
                ('received', models.BooleanField(default=False, verbose_name='دریافت')),
                ('items', models.ManyToManyField(to='cart.OrderItem', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات کاربران',
            },
        ),
    ]
